### PR TITLE
Update runtime to 23.08 and include appdata patch

### LINKED ISSUE #20: Flathub lists Supertux as a proprietary app
The Flathub page incorrectly says this is a proprietary app.

### PR DESCRIPTION
**Pull request by Zishan-Rahman**
As well as updating the Freedesktop runtime, this fixes #20.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Thanks for the PR! Let's hope this will get merged by someone. :-)

**Comment by AsciiWolf** [comment]
@nedrichards @barthalion Any chance you could add me push rights to this (and the Pingus one) repo as I suggested [here](https://github.com/flathub/flathub/issues/4509#issuecomment-1719301497)? Thanks!

**Comment by Newbytee** [comment]
bot, build

**Comment by Newbytee** [comment]
Thanks!

**Pull request merged**
